{"url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/1676","repository_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut","labels_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/1676/labels{/name}","comments_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/1676/comments","events_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/1676/events","html_url":"https://github.com/DeepLabCut/DeepLabCut/issues/1676","id":1127947473,"node_id":"I_kwDOB5BM6c5DOxzR","number":1676,"title":"Can't retrain from snapshot or evaluate after training in colab","user":{"login":"jonpedros","id":85462635,"node_id":"MDQ6VXNlcjg1NDYyNjM1","avatar_url":"https://avatars.githubusercontent.com/u/85462635?v=4","gravatar_id":"","url":"https://api.github.com/users/jonpedros","html_url":"https://github.com/jonpedros","followers_url":"https://api.github.com/users/jonpedros/followers","following_url":"https://api.github.com/users/jonpedros/following{/other_user}","gists_url":"https://api.github.com/users/jonpedros/gists{/gist_id}","starred_url":"https://api.github.com/users/jonpedros/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jonpedros/subscriptions","organizations_url":"https://api.github.com/users/jonpedros/orgs","repos_url":"https://api.github.com/users/jonpedros/repos","events_url":"https://api.github.com/users/jonpedros/events{/privacy}","received_events_url":"https://api.github.com/users/jonpedros/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":{"login":"jeylau","id":30733203,"node_id":"MDQ6VXNlcjMwNzMzMjAz","avatar_url":"https://avatars.githubusercontent.com/u/30733203?v=4","gravatar_id":"","url":"https://api.github.com/users/jeylau","html_url":"https://github.com/jeylau","followers_url":"https://api.github.com/users/jeylau/followers","following_url":"https://api.github.com/users/jeylau/following{/other_user}","gists_url":"https://api.github.com/users/jeylau/gists{/gist_id}","starred_url":"https://api.github.com/users/jeylau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jeylau/subscriptions","organizations_url":"https://api.github.com/users/jeylau/orgs","repos_url":"https://api.github.com/users/jeylau/repos","events_url":"https://api.github.com/users/jeylau/events{/privacy}","received_events_url":"https://api.github.com/users/jeylau/received_events","type":"User","site_admin":false},"assignees":[{"login":"jeylau","id":30733203,"node_id":"MDQ6VXNlcjMwNzMzMjAz","avatar_url":"https://avatars.githubusercontent.com/u/30733203?v=4","gravatar_id":"","url":"https://api.github.com/users/jeylau","html_url":"https://github.com/jeylau","followers_url":"https://api.github.com/users/jeylau/followers","following_url":"https://api.github.com/users/jeylau/following{/other_user}","gists_url":"https://api.github.com/users/jeylau/gists{/gist_id}","starred_url":"https://api.github.com/users/jeylau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jeylau/subscriptions","organizations_url":"https://api.github.com/users/jeylau/orgs","repos_url":"https://api.github.com/users/jeylau/repos","events_url":"https://api.github.com/users/jeylau/events{/privacy}","received_events_url":"https://api.github.com/users/jeylau/received_events","type":"User","site_admin":false}],"milestone":null,"comments":1,"created_at":"2022-02-09T01:40:28Z","updated_at":"2022-02-09T03:14:10Z","closed_at":"2022-02-09T03:13:07Z","author_association":"NONE","active_lock_reason":null,"body":"### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing issues\r\n\r\n### Bug description\r\n\r\nI've been trying to train a model from labeled data on Colab.  I leave it training for iterations until it times out but, after trying to train again from scratch or with weights, I get the following errors. The error is similar when going for evaluating trained models.\r\n\r\nSomething that I noticed is that the pose_cfg.yaml gets its init_weights field changed back to the resnet file after trying to retrain, so my change to the file seems to not make any difference after all.\r\n\r\nI have seen a similar issue in the forum but it did not get solved; removing and installing specific versions of tensorflow only returned a different error. \r\n\r\nIt's also worth mentioning that this only happens after a successful (timed out) model training. After I got this I deleted my project folder from Drive, made a new Colab Notebook copy, re-uploaded my project file with only labeled data (no models), and was able to try training again. But got the same error afterwards.\r\n\r\nAfter that I tried deleting only the dlc_models and training_datasets, along with making a new copy of the colab notebook and still got the same error. Only after reuploading the config.yaml file to its original state I could try training again.\r\n\r\n### Operating System\r\n\r\nGoogle Colab\r\n\r\n### DeepLabCut version\r\n\r\n2.2.0.6\r\n\r\n### DeepLabCut mode\r\n\r\nsingle animal\r\n\r\n### Device type\r\n\r\nPython 3 Google Compute Engine backend (GPU)\r\n\r\n### Steps To Reproduce\r\n\r\n_No response_\r\n\r\n### Relevant log output\r\n\r\n```shell\r\nConfig:\r\n{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7]],\r\n 'all_joints_names': ['right-digit1',\r\n                      'right-digit2',\r\n                      'right-digit3',\r\n                      'right-digit4',\r\n                      'left-digit1',\r\n                      'left-digit2',\r\n                      'left-digit3',\r\n                      'left-digit4'],\r\n 'alpha_r': 0.02,\r\n 'apply_prob': 0.5,\r\n 'batch_size': 1,\r\n 'clahe': True,\r\n 'claheratio': 0.1,\r\n 'crop_pad': 0,\r\n 'crop_sampling': 'hybrid',\r\n 'crop_size': [400, 400],\r\n 'cropratio': 0.4,\r\n 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/dlc_digits_Joao95shuffle1.mat',\r\n 'dataset_type': 'imgaug',\r\n 'decay_steps': 30000,\r\n 'deterministic': False,\r\n 'display_iters': 1000,\r\n 'edge': False,\r\n 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},\r\n 'fg_fraction': 0.25,\r\n 'global_scale': 0.8,\r\n 'histeq': True,\r\n 'histeqratio': 0.1,\r\n 'init_weights': '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',\r\n 'intermediate_supervision': False,\r\n 'intermediate_supervision_layer': 12,\r\n 'location_refinement': True,\r\n 'locref_huber_loss': True,\r\n 'locref_loss_weight': 0.05,\r\n 'locref_stdev': 7.2801,\r\n 'log_dir': 'log',\r\n 'lr_init': 0.0005,\r\n 'max_input_size': 1500,\r\n 'max_shift': 0.4,\r\n 'mean_pixel': [123.68, 116.779, 103.939],\r\n 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/Documentation_data-dlc_digits_95shuffle1.pickle',\r\n 'min_input_size': 64,\r\n 'mirror': False,\r\n 'multi_stage': False,\r\n 'multi_step': [[0.005, 10000],\r\n                [0.02, 430000],\r\n                [0.002, 730000],\r\n                [0.001, 1030000]],\r\n 'net_type': 'resnet_50',\r\n 'num_joints': 8,\r\n 'optimizer': 'sgd',\r\n 'pairwise_huber_loss': False,\r\n 'pairwise_predict': False,\r\n 'partaffinityfield_predict': False,\r\n 'pos_dist_thresh': 17,\r\n 'pre_resize': [],\r\n 'project_path': '/content/drive/My Drive/dlc_digits-Joao-2022-02-08',\r\n 'regularize': False,\r\n 'rotation': 25,\r\n 'rotratio': 0.4,\r\n 'save_iters': 50000,\r\n 'scale_jitter_lo': 0.5,\r\n 'scale_jitter_up': 1.25,\r\n 'scoremap_dir': 'test',\r\n 'sharpen': False,\r\n 'sharpenratio': 0.3,\r\n 'shuffle': True,\r\n 'snapshot_prefix': '/content/drive/My '\r\n                    'Drive/dlc_digits-Joao-2022-02-08/dlc-models/iteration-0/dlc_digitsFeb8-trainset95shuffle1/train/snapshot',\r\n 'stride': 8.0,\r\n 'weigh_negatives': False,\r\n 'weigh_only_present_joints': False,\r\n 'weigh_part_predictions': False,\r\n 'weight_decay': 0.0001}\r\n\r\nSelecting single-animal trainer\r\n\r\n/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.\r\n  warnings.warn('`layer.apply` is deprecated and '\r\n/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.\r\n  outputs = layer.apply(inputs, training=is_training)\r\n\r\nBatch Size is 1\r\nLoading ImageNet-pretrained resnet_50\r\nDisplay_iters overwritten as 10\r\nSave_iters overwritten as 500\r\nTraining parameter:\r\n{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/content/drive/My Drive/dlc_digits-Joao-2022-02-08/dlc-models/iteration-0/dlc_digitsFeb8-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7]], 'all_joints_names': ['right-digit1', 'right-digit2', 'right-digit3', 'right-digit4', 'left-digit1', 'left-digit2', 'left-digit3', 'left-digit4'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/dlc_digits_Joao95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_dlc_digitsFeb8/Documentation_data-dlc_digits_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 8, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': '/content/drive/My Drive/dlc_digits-Joao-2022-02-08', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}\r\nStarting training....\r\n\r\n---------------------------------------------------------------------------\r\n\r\nUnimplementedError                        Traceback (most recent call last)\r\n\r\n/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)\r\n   1376     try:\r\n-> 1377       return fn(*args)\r\n   1378     except errors.OpError as e:\r\n\r\n9 frames\r\n\r\nUnimplementedError: 2 root error(s) found.\r\n  (0) UNIMPLEMENTED: DNN library is not found.\r\n\t [[{{node resnet_v1_50/conv1/Conv2D}}]]\r\n\t [[huber_loss/assert_broadcastable/AssertGuard/pivot_f/_15/_556]]\r\n  (1) UNIMPLEMENTED: DNN library is not found.\r\n\t [[{{node resnet_v1_50/conv1/Conv2D}}]]\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nUnimplementedError                        Traceback (most recent call last)\r\n\r\n/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)\r\n   1394                     '\\nsession_config.graph_options.rewrite_options.'\r\n   1395                     'disable_meta_optimizer = True')\r\n-> 1396       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\r\n   1397 \r\n   1398   def _extend_graph(self):\r\n\r\nUnimplementedError: Graph execution error:\r\n\r\nDetected at node 'resnet_v1_50/conv1/Conv2D' defined at (most recent call last):\r\n    File \"/usr/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n      \"__main__\", mod_spec)\r\n    File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n      exec(code, run_globals)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py\", line 16, in <module>\r\n      app.launch_new_instance()\r\n    File \"/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py\", line 846, in launch_instance\r\n      app.start()\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py\", line 499, in start\r\n      self.io_loop.start()\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py\", line 132, in start\r\n      self.asyncio_loop.run_forever()\r\n    File \"/usr/lib/python3.7/asyncio/base_events.py\", line 541, in run_forever\r\n      self._run_once()\r\n    File \"/usr/lib/python3.7/asyncio/base_events.py\", line 1786, in _run_once\r\n      handle._run()\r\n    File \"/usr/lib/python3.7/asyncio/events.py\", line 88, in _run\r\n      self._context.run(self._callback, *self._args)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py\", line 122, in _handle_events\r\n      handler_func(fileobj, events)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py\", line 300, in null_wrapper\r\n      return fn(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\r\n      self._handle_recv()\r\n    File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\r\n      self._run_callback(callback, msg)\r\n    File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\r\n      callback(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py\", line 300, in null_wrapper\r\n      return fn(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\r\n      return self.dispatch_shell(stream, msg)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\r\n      handler(stream, idents, msg)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 399, in execute_request\r\n      user_expressions, allow_stdin)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py\", line 208, in do_execute\r\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py\", line 537, in run_cell\r\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2718, in run_cell\r\n      interactivity=interactivity, compiler=compiler, result=result)\r\n    File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2828, in run_ast_nodes\r\n      if self.run_code(code, result):\r\n    File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\r\n      exec(code_obj, self.user_global_ns, self.user_ns)\r\n    File \"<ipython-input-10-98176c53e60f>\", line 5, in <module>\r\n      deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=500)\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py\", line 185, in train_network\r\n      allow_growth=allow_growth,\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py\", line 171, in train\r\n      losses = PoseNetFactory.create(cfg).train(batch)\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/base.py\", line 22, in train\r\n      heads = self.get_net(batch[Batch.inputs])\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py\", line 76, in get_net\r\n      net, end_points = self.extract_features(inputs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py\", line 43, in extract_features\r\n      is_training=False,\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py\", line 279, in resnet_v1_50\r\n      scope=scope)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py\", line 210, in resnet_v1\r\n      net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_utils.py\", line 150, in conv2d_same\r\n      scope=scope)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py\", line 184, in func_with_args\r\n      return func(*args, **current_args)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py\", line 1191, in convolution2d\r\n      conv_dims=2)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py\", line 184, in func_with_args\r\n      return func(*args, **current_args)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py\", line 1089, in convolution\r\n      outputs = layer.apply(inputs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py\", line 1697, in apply\r\n      return self.__call__(inputs, *args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py\", line 568, in __call__\r\n      outputs = super(Layer, self).__call__(inputs, *args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py\", line 784, in __call__\r\n      outputs = call_fn(cast_inputs, *args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py\", line 253, in call\r\n      outputs = self._convolution_op(inputs, self.kernel)\r\nNode: 'resnet_v1_50/conv1/Conv2D'\r\nDetected at node 'resnet_v1_50/conv1/Conv2D' defined at (most recent call last):\r\n    File \"/usr/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n      \"__main__\", mod_spec)\r\n    File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n      exec(code, run_globals)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py\", line 16, in <module>\r\n      app.launch_new_instance()\r\n    File \"/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py\", line 846, in launch_instance\r\n      app.start()\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py\", line 499, in start\r\n      self.io_loop.start()\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py\", line 132, in start\r\n      self.asyncio_loop.run_forever()\r\n    File \"/usr/lib/python3.7/asyncio/base_events.py\", line 541, in run_forever\r\n      self._run_once()\r\n    File \"/usr/lib/python3.7/asyncio/base_events.py\", line 1786, in _run_once\r\n      handle._run()\r\n    File \"/usr/lib/python3.7/asyncio/events.py\", line 88, in _run\r\n      self._context.run(self._callback, *self._args)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py\", line 122, in _handle_events\r\n      handler_func(fileobj, events)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py\", line 300, in null_wrapper\r\n      return fn(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\r\n      self._handle_recv()\r\n    File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\r\n      self._run_callback(callback, msg)\r\n    File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\r\n      callback(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py\", line 300, in null_wrapper\r\n      return fn(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\r\n      return self.dispatch_shell(stream, msg)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\r\n      handler(stream, idents, msg)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 399, in execute_request\r\n      user_expressions, allow_stdin)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py\", line 208, in do_execute\r\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\r\n    File \"/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py\", line 537, in run_cell\r\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2718, in run_cell\r\n      interactivity=interactivity, compiler=compiler, result=result)\r\n    File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2828, in run_ast_nodes\r\n      if self.run_code(code, result):\r\n    File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\r\n      exec(code_obj, self.user_global_ns, self.user_ns)\r\n    File \"<ipython-input-10-98176c53e60f>\", line 5, in <module>\r\n      deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=500)\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py\", line 185, in train_network\r\n      allow_growth=allow_growth,\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py\", line 171, in train\r\n      losses = PoseNetFactory.create(cfg).train(batch)\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/base.py\", line 22, in train\r\n      heads = self.get_net(batch[Batch.inputs])\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py\", line 76, in get_net\r\n      net, end_points = self.extract_features(inputs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py\", line 43, in extract_features\r\n      is_training=False,\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py\", line 279, in resnet_v1_50\r\n      scope=scope)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py\", line 210, in resnet_v1\r\n      net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_utils.py\", line 150, in conv2d_same\r\n      scope=scope)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py\", line 184, in func_with_args\r\n      return func(*args, **current_args)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py\", line 1191, in convolution2d\r\n      conv_dims=2)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py\", line 184, in func_with_args\r\n      return func(*args, **current_args)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py\", line 1089, in convolution\r\n      outputs = layer.apply(inputs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py\", line 1697, in apply\r\n      return self.__call__(inputs, *args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py\", line 568, in __call__\r\n      outputs = super(Layer, self).__call__(inputs, *args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py\", line 784, in __call__\r\n      outputs = call_fn(cast_inputs, *args, **kwargs)\r\n    File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py\", line 253, in call\r\n      outputs = self._convolution_op(inputs, self.kernel)\r\nNode: 'resnet_v1_50/conv1/Conv2D'\r\n2 root error(s) found.\r\n  (0) UNIMPLEMENTED: DNN library is not found.\r\n\t [[{{node resnet_v1_50/conv1/Conv2D}}]]\r\n\t [[huber_loss/assert_broadcastable/AssertGuard/pivot_f/_15/_556]]\r\n  (1) UNIMPLEMENTED: DNN library is not found.\r\n\t [[{{node resnet_v1_50/conv1/Conv2D}}]]\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nOriginal stack trace for 'resnet_v1_50/conv1/Conv2D':\r\n  File \"/usr/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py\", line 16, in <module>\r\n    app.launch_new_instance()\r\n  File \"/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py\", line 846, in launch_instance\r\n    app.start()\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py\", line 499, in start\r\n    self.io_loop.start()\r\n  File \"/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py\", line 132, in start\r\n    self.asyncio_loop.run_forever()\r\n  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 541, in run_forever\r\n    self._run_once()\r\n  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 1786, in _run_once\r\n    handle._run()\r\n  File \"/usr/lib/python3.7/asyncio/events.py\", line 88, in _run\r\n    self._context.run(self._callback, *self._args)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py\", line 122, in _handle_events\r\n    handler_func(fileobj, events)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py\", line 300, in null_wrapper\r\n    return fn(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 452, in _handle_events\r\n    self._handle_recv()\r\n  File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 481, in _handle_recv\r\n    self._run_callback(callback, msg)\r\n  File \"/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py\", line 431, in _run_callback\r\n    callback(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py\", line 300, in null_wrapper\r\n    return fn(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\r\n    return self.dispatch_shell(stream, msg)\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\r\n    handler(stream, idents, msg)\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py\", line 399, in execute_request\r\n    user_expressions, allow_stdin)\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py\", line 208, in do_execute\r\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\r\n  File \"/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py\", line 537, in run_cell\r\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2718, in run_cell\r\n    interactivity=interactivity, compiler=compiler, result=result)\r\n  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2828, in run_ast_nodes\r\n    if self.run_code(code, result):\r\n  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\r\n    exec(code_obj, self.user_global_ns, self.user_ns)\r\n  File \"<ipython-input-10-98176c53e60f>\", line 5, in <module>\r\n    deeplabcut.train_network(path_config_file, shuffle=1, displayiters=10,saveiters=500)\r\n  File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py\", line 185, in train_network\r\n    allow_growth=allow_growth,\r\n  File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py\", line 171, in train\r\n    losses = PoseNetFactory.create(cfg).train(batch)\r\n  File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/base.py\", line 22, in train\r\n    heads = self.get_net(batch[Batch.inputs])\r\n  File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py\", line 76, in get_net\r\n    net, end_points = self.extract_features(inputs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/nnets/resnet.py\", line 43, in extract_features\r\n    is_training=False,\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py\", line 279, in resnet_v1_50\r\n    scope=scope)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_v1.py\", line 210, in resnet_v1\r\n    net = resnet_utils.conv2d_same(net, 64, 7, stride=2, scope='conv1')\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/nets/resnet_utils.py\", line 150, in conv2d_same\r\n    scope=scope)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py\", line 184, in func_with_args\r\n    return func(*args, **current_args)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py\", line 1191, in convolution2d\r\n    conv_dims=2)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/ops/arg_scope.py\", line 184, in func_with_args\r\n    return func(*args, **current_args)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py\", line 1089, in convolution\r\n    outputs = layer.apply(inputs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py\", line 1697, in apply\r\n    return self.__call__(inputs, *args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/legacy_tf_layers/base.py\", line 568, in __call__\r\n    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py\", line 784, in __call__\r\n    outputs = call_fn(cast_inputs, *args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\r\n    return converted_call(f, args, kwargs, options=options)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py\", line 377, in converted_call\r\n    return _call_unconverted(f, args, kwargs, options)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\r\n    return f(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py\", line 253, in call\r\n    outputs = self._convolution_op(inputs, self.kernel)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\r\n    return fn(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py\", line 1082, in op_dispatch_handler\r\n    return dispatch_target(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py\", line 1155, in convolution_v2\r\n    name=name)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py\", line 1287, in convolution_internal\r\n    name=name)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py\", line 2763, in _conv2d_expanded_batch\r\n    name=name)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py\", line 973, in conv2d\r\n    data_format=data_format, dilations=dilations, name=name)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py\", line 742, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py\", line 3784, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py\", line 2175, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op)\r\n```\r\n\r\n\r\n### Anything else?\r\n\r\nI had the runtime hanging undefinetely for the DeepLabCut install during the statmodels dependency installation, which I fixed by upgrading pip install. I had errors when creating the training dataset with tables' version but fixed it by upgrading it and then running the DLC pip install again.\r\n\r\n### Code of Conduct\r\n\r\n- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)","closed_by":{"login":"jonpedros","id":85462635,"node_id":"MDQ6VXNlcjg1NDYyNjM1","avatar_url":"https://avatars.githubusercontent.com/u/85462635?v=4","gravatar_id":"","url":"https://api.github.com/users/jonpedros","html_url":"https://github.com/jonpedros","followers_url":"https://api.github.com/users/jonpedros/followers","following_url":"https://api.github.com/users/jonpedros/following{/other_user}","gists_url":"https://api.github.com/users/jonpedros/gists{/gist_id}","starred_url":"https://api.github.com/users/jonpedros/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jonpedros/subscriptions","organizations_url":"https://api.github.com/users/jonpedros/orgs","repos_url":"https://api.github.com/users/jonpedros/repos","events_url":"https://api.github.com/users/jonpedros/events{/privacy}","received_events_url":"https://api.github.com/users/jonpedros/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/1676/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/1676/timeline","performed_via_github_app":null,"state_reason":"completed"}