{"url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/8","repository_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut","labels_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/8/labels{/name}","comments_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/8/comments","events_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/8/events","html_url":"https://github.com/DeepLabCut/DeepLabCut/issues/8","id":320888805,"node_id":"MDU6SXNzdWUzMjA4ODg4MDU=","number":8,"title":"Step1_EvaluateModelon...py: Error when snapshotindex = all","user":{"login":"mcamila777","id":16735161,"node_id":"MDQ6VXNlcjE2NzM1MTYx","avatar_url":"https://avatars.githubusercontent.com/u/16735161?v=4","gravatar_id":"","url":"https://api.github.com/users/mcamila777","html_url":"https://github.com/mcamila777","followers_url":"https://api.github.com/users/mcamila777/followers","following_url":"https://api.github.com/users/mcamila777/following{/other_user}","gists_url":"https://api.github.com/users/mcamila777/gists{/gist_id}","starred_url":"https://api.github.com/users/mcamila777/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mcamila777/subscriptions","organizations_url":"https://api.github.com/users/mcamila777/orgs","repos_url":"https://api.github.com/users/mcamila777/repos","events_url":"https://api.github.com/users/mcamila777/events{/privacy}","received_events_url":"https://api.github.com/users/mcamila777/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":8,"created_at":"2018-05-07T17:32:59Z","updated_at":"2018-06-18T22:38:28Z","closed_at":"2018-05-08T21:16:49Z","author_association":"NONE","active_lock_reason":null,"body":"To evaluate all models (snapshots of training stages) I set on `myconfig.py` the variable `snapshotindex = all`.\r\n\r\nThere is a variable mistake in the `Step1_EvaluateModelonDataset.py` file, since the conditioned variable `snapindex` was not used, but the imported variable `snapshotindex` was.  \r\nCorrection:\r\n\r\n```\r\n        ##################################################\r\n        # Compute predictions over images\r\n        ##################################################\r\n\r\n        if snapshotindex == -1:\r\n            snapindices = [-1]\r\n        elif snapshotindex == all:\r\n            snapindices = range(len(Snapshots))\r\n        else:\r\n            print(\"Invalid choice, only -1 or all!\")\r\n\r\n        for snapindex in snapindices:\r\n            cfg['init_weights'] = modelfolder + \\\r\n                '/train/' + Snapshots[snapindex] # xxx[snapshotindex]\r\n            trainingsiterations = (\r\n                cfg['init_weights'].split('/')[-1]).split('-')[-1]\r\n            scorer = 'DeepCut' + \"_resnet\" + str(cfg[\"net_type\"]) + \"_\" + str(\r\n                int(trainFraction *\r\n                    100)) + 'shuffle' + str(shuffle) + '_' + str(\r\n                        trainingsiterations) + \"forTask:\" + Task\r\n\r\n            print(\"Running \", scorer, trainingsiterations)\r\n\r\n            try:\r\n                Data = pd.read_hdf('Data_h5/' + scorer + '.h5',\r\n                                   'df_with_missing')\r\n                print(\"This net has already been evaluated!\")\r\n            except:\r\n                # Specifying state of model (snapshot / training state)\r\n                cfg['init_weights'] = modelfolder + \\\r\n                    '/train/' + Snapshots[snapindex] # xxx[snapshotindex]\r\n                sess, inputs, outputs = predict.setup_pose_prediction(cfg)\r\n```\r\n\r\n\r\nHowever, there is still a tf error when running this script in this mode:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"Step1_EvaluateModelonDataset.py\", line 132, in <module>\r\n    sess, inputs, outputs = **predict**.setup_pose_prediction(cfg)\r\n...\r\n\r\n**_ValueError:** Variable resnet_v1_50/conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:\r\n\r\n  File \"/tensorflow-3.0/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py\", line 216, in variable\r\n    use_resource=use_resource)\r\n\r\n...\r\n```\r\n\r\nTo solve this what I did (it worked but not sure if it is the best solution) is to [reset the graph](https://github.com/kratzert/finetune_alexnet_with_tensorflow/issues/8) for each new iteration of snapshots. By adding  `tf.reset_default_graph()`  to the method `setup_pose_prediction(cfg)` of the file `DeepLabCut/pose-tensorflow/nnet/predict.py`\r\n\r\n```\r\n\r\ndef setup_pose_prediction(cfg):\r\n    tf.reset_default_graph() # NEW LINE\r\n    inputs = tf.placeholder(tf.float32, shape=[cfg.batch_size   , None, None, 3])\r\n\r\n    net_heads = pose_net(cfg).test(inputs)\r\n    outputs = [net_heads['part_prob']]\r\n    if cfg.location_refinement:\r\n        outputs.append(net_heads['locref'])\r\n\r\n    restorer = tf.train.Saver()\r\n\r\n    sess = tf.Session()\r\n\r\n    sess.run(tf.global_variables_initializer())\r\n    sess.run(tf.local_variables_initializer())\r\n\r\n    # Restore variables from disk.\r\n    restorer.restore(sess, cfg.init_weights)\r\n\r\n    return sess, inputs, outputs\r\n\r\n```","closed_by":{"login":"AlexEMG","id":20850270,"node_id":"MDQ6VXNlcjIwODUwMjcw","avatar_url":"https://avatars.githubusercontent.com/u/20850270?v=4","gravatar_id":"","url":"https://api.github.com/users/AlexEMG","html_url":"https://github.com/AlexEMG","followers_url":"https://api.github.com/users/AlexEMG/followers","following_url":"https://api.github.com/users/AlexEMG/following{/other_user}","gists_url":"https://api.github.com/users/AlexEMG/gists{/gist_id}","starred_url":"https://api.github.com/users/AlexEMG/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AlexEMG/subscriptions","organizations_url":"https://api.github.com/users/AlexEMG/orgs","repos_url":"https://api.github.com/users/AlexEMG/repos","events_url":"https://api.github.com/users/AlexEMG/events{/privacy}","received_events_url":"https://api.github.com/users/AlexEMG/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/8/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/DeepLabCut/DeepLabCut/issues/8/timeline","performed_via_github_app":null,"state_reason":"completed"}