{"url":"https://api.github.com/repos/topazape/LSTM_Chem/issues/6","repository_url":"https://api.github.com/repos/topazape/LSTM_Chem","labels_url":"https://api.github.com/repos/topazape/LSTM_Chem/issues/6/labels{/name}","comments_url":"https://api.github.com/repos/topazape/LSTM_Chem/issues/6/comments","events_url":"https://api.github.com/repos/topazape/LSTM_Chem/issues/6/events","html_url":"https://github.com/topazape/LSTM_Chem/issues/6","id":585691484,"node_id":"MDU6SXNzdWU1ODU2OTE0ODQ=","number":6,"title":"RuntimeError: dictionary changed size during iteration","user":{"login":"marz869","id":24370421,"node_id":"MDQ6VXNlcjI0MzcwNDIx","avatar_url":"https://avatars.githubusercontent.com/u/24370421?v=4","gravatar_id":"","url":"https://api.github.com/users/marz869","html_url":"https://github.com/marz869","followers_url":"https://api.github.com/users/marz869/followers","following_url":"https://api.github.com/users/marz869/following{/other_user}","gists_url":"https://api.github.com/users/marz869/gists{/gist_id}","starred_url":"https://api.github.com/users/marz869/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/marz869/subscriptions","organizations_url":"https://api.github.com/users/marz869/orgs","repos_url":"https://api.github.com/users/marz869/repos","events_url":"https://api.github.com/users/marz869/events{/privacy}","received_events_url":"https://api.github.com/users/marz869/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2020-03-22T10:54:11Z","updated_at":"2020-06-08T07:28:11Z","closed_at":"2020-06-08T07:28:11Z","author_association":"NONE","active_lock_reason":null,"body":"Hi \r\nThanks for your great job.\r\nAt the end of epoch 2 before saving model and last iteration I got this error:\r\n`Exception in thread Thread-2:\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\threading.py\", line 926, in _bootstrap_inner\r\n    self.run()\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\threading.py\", line 870, in run\r\n    self._target(*self._args, **self._kwargs)\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\site-packages\\tensorflow_core\\python\\keras\\utils\\data_utils.py\", line 748, in _run\r\n    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\site-packages\\tensorflow_core\\python\\keras\\utils\\data_utils.py\", line 727, in pool_fn\r\n    initargs=(seqs, None, get_worker_id_queue()))\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\context.py\", line 119, in Pool\r\n    context=self.get_context())\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\pool.py\", line 176, in __init__\r\n    self._repopulate_pool()\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\pool.py\", line 241, in _repopulate_pool\r\n    w.start()\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\process.py\", line 112, in start\r\n    self._popen = self._Popen(self)\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\context.py\", line 322, in _Popen\r\n    return Popen(process_obj)\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\popen_spawn_win32.py\", line 89, in __init__\r\n    reduction.dump(process_obj, to_child)\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\reduction.py\", line 60, in dump\r\n    ForkingPickler(file, protocol).dump(obj)\r\nRuntimeError: dictionary changed size during iteration\r\n\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\spawn.py\", line 105, in spawn_main\r\n    exitcode = _main(fd)\r\n  File \"C:\\Users\\Radical\\Anaconda3\\envs\\myenv\\lib\\multiprocessing\\spawn.py\", line 115, in _main\r\n    self = reduction.pickle.load(from_parent)\r\nEOFError: Ran out of input`\r\n\r\nwould you explain why it is happening or fixed it.. thank you.","closed_by":{"login":"topazape","id":38512143,"node_id":"MDQ6VXNlcjM4NTEyMTQz","avatar_url":"https://avatars.githubusercontent.com/u/38512143?v=4","gravatar_id":"","url":"https://api.github.com/users/topazape","html_url":"https://github.com/topazape","followers_url":"https://api.github.com/users/topazape/followers","following_url":"https://api.github.com/users/topazape/following{/other_user}","gists_url":"https://api.github.com/users/topazape/gists{/gist_id}","starred_url":"https://api.github.com/users/topazape/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/topazape/subscriptions","organizations_url":"https://api.github.com/users/topazape/orgs","repos_url":"https://api.github.com/users/topazape/repos","events_url":"https://api.github.com/users/topazape/events{/privacy}","received_events_url":"https://api.github.com/users/topazape/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/topazape/LSTM_Chem/issues/6/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/topazape/LSTM_Chem/issues/6/timeline","performed_via_github_app":null,"state_reason":"completed"}