{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/692","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/692/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/692/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/692/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/692","id":593943401,"node_id":"MDU6SXNzdWU1OTM5NDM0MDE=","number":692,"title":"xseg training - latest update error","user":{"login":"jejz","id":19254175,"node_id":"MDQ6VXNlcjE5MjU0MTc1","avatar_url":"https://avatars.githubusercontent.com/u/19254175?v=4","gravatar_id":"","url":"https://api.github.com/users/jejz","html_url":"https://github.com/jejz","followers_url":"https://api.github.com/users/jejz/followers","following_url":"https://api.github.com/users/jejz/following{/other_user}","gists_url":"https://api.github.com/users/jejz/gists{/gist_id}","starred_url":"https://api.github.com/users/jejz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jejz/subscriptions","organizations_url":"https://api.github.com/users/jejz/orgs","repos_url":"https://api.github.com/users/jejz/repos","events_url":"https://api.github.com/users/jejz/events{/privacy}","received_events_url":"https://api.github.com/users/jejz/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2020-04-04T16:24:50Z","updated_at":"2020-04-06T17:12:25Z","closed_at":"2020-04-06T17:12:25Z","author_association":"NONE","active_lock_reason":null,"body":"Loading samples: 100%|############################################################| 6256/6256 [00:22<00:00, 281.68it/s]\r\nLoading samples: 100%|##########################################################| 34188/34188 [00:47<00:00, 725.82it/s]\r\nUsing 290 segmented samples.\r\nException in thread Thread-14:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nOverflowError: cannot serialize a bytes object larger than 4 GiB\r\n\r\nException in thread Thread-15:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nOverflowError: cannot serialize a bytes object larger than 4 GiB\r\nException in thread Thread-16:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nOverflowError: cannot serialize a bytes object larger than 4 GiB\r\n\r\n\r\nException in thread Thread-17:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\DeepFaceLab_NVIDIA\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nOverflowError: cannot serialize a bytes object larger than 4 GiB\r\n\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"multiprocessing\\spawn.py\", line 105, in spawn_main\r\n  File \"multiprocessing\\spawn.py\", line 115, in _main\r\nEOFError: Ran out of input\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"multiprocessing\\spawn.py\", line 105, in spawn_main\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"multiprocessing\\spawn.py\", line 115, in _main\r\n  File \"multiprocessing\\spawn.py\", line 105, in spawn_main\r\nEOFError: Ran out of input\r\n  File \"multiprocessing\\spawn.py\", line 115, in _main\r\nEOFError: Ran out of input\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"multiprocessing\\spawn.py\", line 105, in spawn_main\r\n  File \"multiprocessing\\spawn.py\", line 115, in _main\r\nEOFError: Ran out of input","closed_by":{"login":"iperov","id":8076202,"node_id":"MDQ6VXNlcjgwNzYyMDI=","avatar_url":"https://avatars.githubusercontent.com/u/8076202?v=4","gravatar_id":"","url":"https://api.github.com/users/iperov","html_url":"https://github.com/iperov","followers_url":"https://api.github.com/users/iperov/followers","following_url":"https://api.github.com/users/iperov/following{/other_user}","gists_url":"https://api.github.com/users/iperov/gists{/gist_id}","starred_url":"https://api.github.com/users/iperov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/iperov/subscriptions","organizations_url":"https://api.github.com/users/iperov/orgs","repos_url":"https://api.github.com/users/iperov/repos","events_url":"https://api.github.com/users/iperov/events{/privacy}","received_events_url":"https://api.github.com/users/iperov/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/692/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/692/timeline","performed_via_github_app":null,"state_reason":"completed"}