{"url":"https://api.github.com/repos/sktime/sktime/issues/1555","repository_url":"https://api.github.com/repos/sktime/sktime","labels_url":"https://api.github.com/repos/sktime/sktime/issues/1555/labels{/name}","comments_url":"https://api.github.com/repos/sktime/sktime/issues/1555/comments","events_url":"https://api.github.com/repos/sktime/sktime/issues/1555/events","html_url":"https://github.com/sktime/sktime/issues/1555","id":1034665265,"node_id":"I_kwDOCVKAsc49q70x","number":1555,"title":"[BUG] AssertionError when using `pd.PeriodIndex` forecasting horizon with `freq=\"H\"`","user":{"login":"sameermahajan","id":4393655,"node_id":"MDQ6VXNlcjQzOTM2NTU=","avatar_url":"https://avatars.githubusercontent.com/u/4393655?v=4","gravatar_id":"","url":"https://api.github.com/users/sameermahajan","html_url":"https://github.com/sameermahajan","followers_url":"https://api.github.com/users/sameermahajan/followers","following_url":"https://api.github.com/users/sameermahajan/following{/other_user}","gists_url":"https://api.github.com/users/sameermahajan/gists{/gist_id}","starred_url":"https://api.github.com/users/sameermahajan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sameermahajan/subscriptions","organizations_url":"https://api.github.com/users/sameermahajan/orgs","repos_url":"https://api.github.com/users/sameermahajan/repos","events_url":"https://api.github.com/users/sameermahajan/events{/privacy}","received_events_url":"https://api.github.com/users/sameermahajan/received_events","type":"User","site_admin":false},"labels":[{"id":1118163262,"node_id":"MDU6TGFiZWwxMTE4MTYzMjYy","url":"https://api.github.com/repos/sktime/sktime/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"},{"id":3105906374,"node_id":"MDU6TGFiZWwzMTA1OTA2Mzc0","url":"https://api.github.com/repos/sktime/sktime/labels/module:forecasting","name":"module:forecasting","color":"35FCCE","default":false,"description":""}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2021-10-25T04:29:19Z","updated_at":"2022-01-12T21:53:20Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\nI have  fitted a model over a series that looks something like:\r\n\r\nds\r\n2021-10-14 18:12:00    22811316.0\r\n2021-10-14 18:42:00    22700704.0\r\n2021-10-14 18:43:00    22439784.0\r\n2021-10-14 18:44:00    22979880.0\r\n2021-10-14 18:45:00    23051732.0\r\n                          ...    \r\n2021-10-17 17:07:32    26841748.0\r\n2021-10-17 17:34:32    26620540.0\r\n2021-10-17 17:35:32    27671180.0\r\n2021-10-17 17:36:32    27202980.0\r\n2021-10-17 17:37:32    27075036.0\r\nLength: 441, dtype: float64\r\n\r\nThe fit succeeds. However when I try to  predict over a forecasting horizon as:\r\n\r\nfh = ForecastingHorizon(\r\n    pd.PeriodIndex(pd.date_range(start=\"2021-10-17 18:37:32\", periods=24, freq=\"H\")), is_relative=False\r\n)\r\nforecaster.fit(series)\r\ny_pred = forecaster.predict(fh)\r\n\r\nI get an AssertionError as:\r\n\r\nAssertionError                            Traceback (most recent call last)\r\n<ipython-input-23-52fbc49722c4> in <module>\r\n      5 #fh = np.arange(1, 2)\r\n      6 forecaster.fit(series)\r\n----> 7 y_pred = forecaster.predict(fh)\r\n\r\n~/.local/lib/python3.8/site-packages/sktime/forecasting/base/_base.py in predict(self, fh, X, return_pred_int, alpha)\r\n    236         # alpha = check_alpha(alpha)\r\n    237 \r\n--> 238         y_pred = self._predict(\r\n    239             self.fh,\r\n    240             X=X_inner,\r\n\r\n~/.local/lib/python3.8/site-packages/sktime/forecasting/base/adapters/_statsmodels.py in _predict(self, fh, X, return_pred_int, alpha)\r\n     81         # statsmodels requires zero-based indexing starting at the\r\n     82         # beginning of the training series when passing integers\r\n---> 83         start, end = fh.to_absolute_int(self._y.index[0], self.cutoff)[[0, -1]]\r\n     84 \r\n     85         if \"exog\" in inspect.signature(self._forecaster.__init__).parameters.keys():\r\n\r\n~/.local/lib/python3.8/site-packages/sktime/forecasting/base/_fh.py in to_absolute_int(self, start, cutoff)\r\n    338         # to convert the horizon to the absolute representation below\r\n    339         absolute = self.to_absolute(cutoff).to_pandas()\r\n--> 340         _check_start(start, absolute)\r\n    341 \r\n    342         # Note: We should here also coerce to periods for more reliable arithmetic\r\n\r\n~/.local/lib/python3.8/site-packages/sktime/forecasting/base/_fh.py in _check_start(start, index)\r\n    499 def _check_start(start, index):\r\n    500     if isinstance(index, pd.PeriodIndex):\r\n--> 501         assert isinstance(start, pd.Period)\r\n    502         assert index.freqstr == start.freqstr\r\n    503 \r\n\r\nAssertionError: \r\n\r\nI tried with a few different values  for start  of forecasting horizon as 2021-10-17 17:37:32 or 2021-10-17 18:00 without luck. What am I missing.\r\n**To Reproduce**\r\nI can provide  my file in .csv and code to load it in pandas Dataframe and convert it into Series for feeding it to fit in case it helps.\r\n\r\nHere is  my file in .csv\r\n[172.17.110.3_172.17.110.4_1974_6_octet.csv](https://github.com/alan-turing-institute/sktime/files/7407263/172.17.110.3_172.17.110.4_1974_6_octet.csv)\r\nand here is my code to read it as pandas Dataframe and convert it to series for  feeding it to fit:\r\n\r\n```python\r\nimport pandas as pd\r\nd = pd.read_csv('172.17.110.3_172.17.110.4_1974_6_octet.csv')\r\nb = d.groupby([\"ds\"]).y.sum().reset_index()\r\nb['ds'] = pd.to_datetime(b['ds'])\r\nb['y'] = b['y'].astype(float)\r\nseries = pd.Series(b.y.values, index=b.ds)\r\n```\r\n```python\r\nfh = ForecastingHorizon(\r\n    pd.PeriodIndex(pd.date_range(start=\"2021-10-17 18:37:32\", periods=24, freq=\"H\")), is_relative=False\r\n)\r\nforecaster.fit(series)\r\ny_pred = forecaster.predict(fh)\r\n```\r\n\r\n**Expected behavior**\r\npredictions should have happened and eventually I should be able to plot them.\r\n\r\n**Additional context**\r\nI have provided  my file in .csv and code to load it in pandas Dataframe and convert it into Series for feeding it to fit in case it helps.\r\n\r\n**Versions**\r\n<details>\r\nSystem:\r\n    python: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]\r\nexecutable: /usr/bin/python3\r\n   machine: Linux-5.11.0-1020-aws-x86_64-with-glibc2.29\r\n\r\nPython dependencies:\r\n          pip: 20.0.2\r\n   setuptools: 45.2.0\r\n      sklearn: 1.0\r\n       sktime: 0.8.0\r\n  statsmodels: 0.13.0\r\n        numpy: 1.21.2\r\n        scipy: 1.7.1\r\n       Cython: 0.29.24\r\n       pandas: 1.3.3\r\n   matplotlib: 3.4.3\r\n       joblib: 1.1.0\r\n        numba: None\r\n     pmdarima: None\r\n      tsfresh: None\r\n</details>\r\n\r\n<!-- Thanks for contributing! -->\r\n","closed_by":null,"reactions":{"url":"https://api.github.com/repos/sktime/sktime/issues/1555/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/sktime/sktime/issues/1555/timeline","performed_via_github_app":null,"state_reason":null}