{"url":"https://api.github.com/repos/experiencor/keras-yolo3/issues/336","repository_url":"https://api.github.com/repos/experiencor/keras-yolo3","labels_url":"https://api.github.com/repos/experiencor/keras-yolo3/issues/336/labels{/name}","comments_url":"https://api.github.com/repos/experiencor/keras-yolo3/issues/336/comments","events_url":"https://api.github.com/repos/experiencor/keras-yolo3/issues/336/events","html_url":"https://github.com/experiencor/keras-yolo3/issues/336","id":1292057172,"node_id":"I_kwDOB6qiN85NAzpU","number":336,"title":"Problem training the model","user":{"login":"TheChief123","id":63095720,"node_id":"MDQ6VXNlcjYzMDk1NzIw","avatar_url":"https://avatars.githubusercontent.com/u/63095720?v=4","gravatar_id":"","url":"https://api.github.com/users/TheChief123","html_url":"https://github.com/TheChief123","followers_url":"https://api.github.com/users/TheChief123/followers","following_url":"https://api.github.com/users/TheChief123/following{/other_user}","gists_url":"https://api.github.com/users/TheChief123/gists{/gist_id}","starred_url":"https://api.github.com/users/TheChief123/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TheChief123/subscriptions","organizations_url":"https://api.github.com/users/TheChief123/orgs","repos_url":"https://api.github.com/users/TheChief123/repos","events_url":"https://api.github.com/users/TheChief123/events{/privacy}","received_events_url":"https://api.github.com/users/TheChief123/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-07-02T13:32:24Z","updated_at":"2022-07-07T09:13:41Z","closed_at":"2022-07-07T09:13:41Z","author_association":"NONE","active_lock_reason":null,"body":"I have successfully installed the packages from requirement.txt.\r\n\r\nI am now working on the kangaroo example.\r\n\r\nWhen I run the code:\r\n\r\n`python train.py -c config.json`\r\n\r\nI get the following error:\r\n\r\n`[Errno 2] No such file or directory: 'valid_annot00147.xml'\r\nIgnore this bad annotation: valid_annot00147.xml`\r\n\r\nThe error is the same through files 00147.xml to 00183.xml in the valid_annot folder which contains .xml annotation files for images 00147 to 00183.\r\n\r\nI am sure that this is not a typo in the `config.json` file. I have also renamed/made new folder etc. Problem stays the same. It cannot access the validation annotations. The folder with annotations is in the same directory as all the other files from this repository.\r\n\r\nBelow is the full terminal output:\r\n\r\n`\r\n(cpu_only) C:\\Users\\Public\\DiplomskaNaloga\\deep\\keras-yolo3-master\\keras-yolo3-master>python train.py -c config.json\r\nUsing TensorFlow backend.\r\n2022-07-02 15:02:14.507225: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found\r\n2022-07-02 15:02:14.507354: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\r\n2022-07-02 15:02:16.190426: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2\r\n2022-07-02 15:02:16.194358: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll\r\n2022-07-02 15:02:16.281043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:\r\nname: Quadro K2100M major: 3 minor: 0 memoryClockRate(GHz): 0.6665\r\npciBusID: 0000:01:00.0\r\n2022-07-02 15:02:16.282220: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found\r\n2022-07-02 15:02:16.284486: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found\r\n2022-07-02 15:02:16.287633: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_100.dll not found\r\n2022-07-02 15:02:16.288589: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64_100.dll not found\r\n2022-07-02 15:02:16.289533: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolver64_100.dll not found\r\n2022-07-02 15:02:16.290489: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cusparse64_100.dll not found\r\n2022-07-02 15:02:16.291538: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found\r\n2022-07-02 15:02:16.291621: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\r\nSkipping registering GPU devices...\r\n2022-07-02 15:02:16.329293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:\r\n2022-07-02 15:02:16.329427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0\r\n2022-07-02 15:02:16.331331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N\r\nWARNING:tensorflow:From train.py:26: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.\r\n\r\n[Errno 2] No such file or directory: 'valid_annot00147.xml'\r\nIgnore this bad annotation: valid_annot00147.xml\r\n[Errno 2] No such file or directory: 'valid_annot00148.xml'\r\nIgnore this bad annotation: valid_annot00148.xml\r\n[Errno 2] No such file or directory: 'valid_annot00149.xml'\r\nIgnore this bad annotation: valid_annot00149.xml\r\n[Errno 2] No such file or directory: 'valid_annot00150.xml'\r\nIgnore this bad annotation: valid_annot00150.xml\r\n[Errno 2] No such file or directory: 'valid_annot00151.xml'\r\nIgnore this bad annotation: valid_annot00151.xml\r\n[Errno 2] No such file or directory: 'valid_annot00152.xml'\r\nIgnore this bad annotation: valid_annot00152.xml\r\n[Errno 2] No such file or directory: 'valid_annot00153.xml'\r\nIgnore this bad annotation: valid_annot00153.xml\r\n[Errno 2] No such file or directory: 'valid_annot00154.xml'\r\nIgnore this bad annotation: valid_annot00154.xml\r\n[Errno 2] No such file or directory: 'valid_annot00155.xml'\r\nIgnore this bad annotation: valid_annot00155.xml\r\n[Errno 2] No such file or directory: 'valid_annot00156.xml'\r\nIgnore this bad annotation: valid_annot00156.xml\r\n[Errno 2] No such file or directory: 'valid_annot00157.xml'\r\nIgnore this bad annotation: valid_annot00157.xml\r\n[Errno 2] No such file or directory: 'valid_annot00158.xml'\r\nIgnore this bad annotation: valid_annot00158.xml\r\n[Errno 2] No such file or directory: 'valid_annot00159.xml'\r\nIgnore this bad annotation: valid_annot00159.xml\r\n[Errno 2] No such file or directory: 'valid_annot00161.xml'\r\nIgnore this bad annotation: valid_annot00161.xml\r\n[Errno 2] No such file or directory: 'valid_annot00162.xml'\r\nIgnore this bad annotation: valid_annot00162.xml\r\n[Errno 2] No such file or directory: 'valid_annot00163.xml'\r\nIgnore this bad annotation: valid_annot00163.xml\r\n[Errno 2] No such file or directory: 'valid_annot00164.xml'\r\nIgnore this bad annotation: valid_annot00164.xml\r\n[Errno 2] No such file or directory: 'valid_annot00166.xml'\r\nIgnore this bad annotation: valid_annot00166.xml\r\n[Errno 2] No such file or directory: 'valid_annot00167.xml'\r\nIgnore this bad annotation: valid_annot00167.xml\r\n[Errno 2] No such file or directory: 'valid_annot00168.xml'\r\nIgnore this bad annotation: valid_annot00168.xml\r\n[Errno 2] No such file or directory: 'valid_annot00169.xml'\r\nIgnore this bad annotation: valid_annot00169.xml\r\n[Errno 2] No such file or directory: 'valid_annot00170.xml'\r\nIgnore this bad annotation: valid_annot00170.xml\r\n[Errno 2] No such file or directory: 'valid_annot00171.xml'\r\nIgnore this bad annotation: valid_annot00171.xml\r\n[Errno 2] No such file or directory: 'valid_annot00172.xml'\r\nIgnore this bad annotation: valid_annot00172.xml\r\n[Errno 2] No such file or directory: 'valid_annot00173.xml'\r\nIgnore this bad annotation: valid_annot00173.xml\r\n[Errno 2] No such file or directory: 'valid_annot00174.xml'\r\nIgnore this bad annotation: valid_annot00174.xml\r\n[Errno 2] No such file or directory: 'valid_annot00175.xml'\r\nIgnore this bad annotation: valid_annot00175.xml\r\n[Errno 2] No such file or directory: 'valid_annot00176.xml'\r\nIgnore this bad annotation: valid_annot00176.xml\r\n[Errno 2] No such file or directory: 'valid_annot00177.xml'\r\nIgnore this bad annotation: valid_annot00177.xml\r\n[Errno 2] No such file or directory: 'valid_annot00178.xml'\r\nIgnore this bad annotation: valid_annot00178.xml\r\n[Errno 2] No such file or directory: 'valid_annot00179.xml'\r\nIgnore this bad annotation: valid_annot00179.xml\r\n[Errno 2] No such file or directory: 'valid_annot00180.xml'\r\nIgnore this bad annotation: valid_annot00180.xml\r\n[Errno 2] No such file or directory: 'valid_annot00181.xml'\r\nIgnore this bad annotation: valid_annot00181.xml\r\n[Errno 2] No such file or directory: 'valid_annot00182.xml'\r\nIgnore this bad annotation: valid_annot00182.xml\r\n[Errno 2] No such file or directory: 'valid_annot00183.xml'\r\nIgnore this bad annotation: valid_annot00183.xml\r\nTraceback (most recent call last):\r\n  File \"train.py\", line 289, in <module>\r\n    _main_(args)\r\n  File \"train.py\", line 191, in _main_\r\n    config['model']['labels']\r\n  File \"train.py\", line 42, in create_training_instances\r\n    valid_ints, valid_labels = parse_voc_annotation(valid_annot_folder, valid_image_folder, valid_cache, labels)\r\n  File \"C:\\Users\\Public\\DiplomskaNaloga\\deep\\keras-yolo3-master\\keras-yolo3-master\\voc.py\", line 64, in parse_voc_annotation\r\n    with open(cache_name, 'wb') as handle:\r\nFileNotFoundError: [Errno 2] No such file or directory: ''\r\n`\r\n\r\nCan anyone help me diagnose this?\r\n\r\nThank you\r\n\r\n\r\n\r\n\r\n","closed_by":{"login":"TheChief123","id":63095720,"node_id":"MDQ6VXNlcjYzMDk1NzIw","avatar_url":"https://avatars.githubusercontent.com/u/63095720?v=4","gravatar_id":"","url":"https://api.github.com/users/TheChief123","html_url":"https://github.com/TheChief123","followers_url":"https://api.github.com/users/TheChief123/followers","following_url":"https://api.github.com/users/TheChief123/following{/other_user}","gists_url":"https://api.github.com/users/TheChief123/gists{/gist_id}","starred_url":"https://api.github.com/users/TheChief123/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TheChief123/subscriptions","organizations_url":"https://api.github.com/users/TheChief123/orgs","repos_url":"https://api.github.com/users/TheChief123/repos","events_url":"https://api.github.com/users/TheChief123/events{/privacy}","received_events_url":"https://api.github.com/users/TheChief123/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/experiencor/keras-yolo3/issues/336/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/experiencor/keras-yolo3/issues/336/timeline","performed_via_github_app":null,"state_reason":"completed"}