{"url":"https://api.github.com/repos/aws-samples/deep-learning-models/issues/43","repository_url":"https://api.github.com/repos/aws-samples/deep-learning-models","labels_url":"https://api.github.com/repos/aws-samples/deep-learning-models/issues/43/labels{/name}","comments_url":"https://api.github.com/repos/aws-samples/deep-learning-models/issues/43/comments","events_url":"https://api.github.com/repos/aws-samples/deep-learning-models/issues/43/events","html_url":"https://github.com/aws-samples/deep-learning-models/issues/43","id":729905096,"node_id":"MDU6SXNzdWU3Mjk5MDUwOTY=","number":43,"title":"Albert does not run locally due to FSx data source","user":{"login":"Cpruce","id":2712171,"node_id":"MDQ6VXNlcjI3MTIxNzE=","avatar_url":"https://avatars.githubusercontent.com/u/2712171?v=4","gravatar_id":"","url":"https://api.github.com/users/Cpruce","html_url":"https://github.com/Cpruce","followers_url":"https://api.github.com/users/Cpruce/followers","following_url":"https://api.github.com/users/Cpruce/following{/other_user}","gists_url":"https://api.github.com/users/Cpruce/gists{/gist_id}","starred_url":"https://api.github.com/users/Cpruce/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Cpruce/subscriptions","organizations_url":"https://api.github.com/users/Cpruce/orgs","repos_url":"https://api.github.com/users/Cpruce/repos","events_url":"https://api.github.com/users/Cpruce/events{/privacy}","received_events_url":"https://api.github.com/users/Cpruce/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2020-10-26T21:03:00Z","updated_at":"2020-10-26T21:03:00Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Error:\r\n\r\n```\r\nroot@6eca14cacd82:/shared/sm_bert_tf/tf2/deep-learning-models/models/nlp# ./launch.sh\r\nwandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.\r\n2020-10-26 13:42:31.332706: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\r\nParameter distribution will be renamed to {'mpi': {'enabled': True, 'processes_per_host': 8, 'custom_mpi_options': '-verbose --NCCL_DEBUG=INFO -x OMPI_MCA_btl_vader_single_copy_mechanism=none'}} in SageMaker Python SDK v2.\r\nParameter image_name will be renamed to image_uri in SageMaker Python SDK v2.\r\nDATA_SOURCE {'FileSystemDataSource': {'FileSystemId': 'fs-0d3f0dfc5f6428d70', 'FileSystemType': 'FSxLustre', 'DirectoryPath': '/fsx', 'FileSystemAccessMode': 'rw'}}\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/shared/sm_bert_tf/tf2/deep-learning-models/models/nlp/albert/launch_sagemaker.py\", line 63, in <module>\r\n    security_group_ids=sm_args.security_group_ids,\r\n  File \"/shared/sm_bert_tf/tf2/deep-learning-models/models/nlp/common/sagemaker_utils.py\", line 97, in launch_sagemaker_job\r\n    estimator_hvd.fit(fsx_input)\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/tensorflow/estimator.py\", line 483, in fit\r\n    fit_super()\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/tensorflow/estimator.py\", line 462, in fit_super\r\n    super(TensorFlow, self).fit(inputs, wait, logs, job_name, experiment_config)\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/estimator.py\", line 496, in fit\r\n    self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_config)\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/estimator.py\", line 1091, in start_new\r\n    estimator.sagemaker_session.train(**train_args)\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/session.py\", line 590, in train\r\n    self.sagemaker_client.create_training_job(**train_request)\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/local/local_session.py\", line 102, in create_training_job\r\n    training_job.start(InputDataConfig, OutputDataConfig, hyperparameters, TrainingJobName)\r\n  File \"/usr/local/lib/python3.7/dist-packages/sagemaker/local/entities.py\", line 80, in start\r\n    \"Need channel['DataSource'] to have ['S3DataSource'] or ['FileDataSource']\"\r\nValueError: Need channel['DataSource'] to have ['S3DataSource'] or ['FileDataSource']\r\n```\r\n\r\nThis is due to the `FileSystemDataSource` not being supported by `_LocalTrainingJob`","closed_by":null,"reactions":{"url":"https://api.github.com/repos/aws-samples/deep-learning-models/issues/43/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/aws-samples/deep-learning-models/issues/43/timeline","performed_via_github_app":null,"state_reason":null}