{"url":"https://api.github.com/repos/google-research/google-research/issues/51","repository_url":"https://api.github.com/repos/google-research/google-research","labels_url":"https://api.github.com/repos/google-research/google-research/issues/51/labels{/name}","comments_url":"https://api.github.com/repos/google-research/google-research/issues/51/comments","events_url":"https://api.github.com/repos/google-research/google-research/issues/51/events","html_url":"https://github.com/google-research/google-research/issues/51","id":487161197,"node_id":"MDU6SXNzdWU0ODcxNjExOTc=","number":51,"title":"FailedPreconditionError:2 root erros","user":{"login":"baolonghnu","id":34078389,"node_id":"MDQ6VXNlcjM0MDc4Mzg5","avatar_url":"https://avatars.githubusercontent.com/u/34078389?v=4","gravatar_id":"","url":"https://api.github.com/users/baolonghnu","html_url":"https://github.com/baolonghnu","followers_url":"https://api.github.com/users/baolonghnu/followers","following_url":"https://api.github.com/users/baolonghnu/following{/other_user}","gists_url":"https://api.github.com/users/baolonghnu/gists{/gist_id}","starred_url":"https://api.github.com/users/baolonghnu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/baolonghnu/subscriptions","organizations_url":"https://api.github.com/users/baolonghnu/orgs","repos_url":"https://api.github.com/users/baolonghnu/repos","events_url":"https://api.github.com/users/baolonghnu/events{/privacy}","received_events_url":"https://api.github.com/users/baolonghnu/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2019-08-29T20:29:18Z","updated_at":"2020-01-28T14:47:12Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hi, I am running into the issue related to FailedPreconditionError: 2 root error, when I am trying to run the train.py within Unprocessing Images for Learned Raw Denoising.  Do you have any idea why this will happen and how to address it. I am using tf_gpu_1.12.0, python 3.5.8, cuda 9.0, Linux. Thanks\r\n\r\n![image](https://user-images.githubusercontent.com/34078389/63974085-f950bd00-ca60-11e9-8a6b-bd4cb5e18c3d.png)","closed_by":null,"reactions":{"url":"https://api.github.com/repos/google-research/google-research/issues/51/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/google-research/google-research/issues/51/timeline","performed_via_github_app":null,"state_reason":null}