{"url":"https://api.github.com/repos/regel/loudml/issues/456","repository_url":"https://api.github.com/repos/regel/loudml","labels_url":"https://api.github.com/repos/regel/loudml/issues/456/labels{/name}","comments_url":"https://api.github.com/repos/regel/loudml/issues/456/comments","events_url":"https://api.github.com/repos/regel/loudml/issues/456/events","html_url":"https://github.com/regel/loudml/issues/456","id":728787584,"node_id":"MDU6SXNzdWU3Mjg3ODc1ODQ=","number":456,"title":"Training Fails: Not JSON Serializable","user":{"login":"lmangani","id":1423657,"node_id":"MDQ6VXNlcjE0MjM2NTc=","avatar_url":"https://avatars.githubusercontent.com/u/1423657?v=4","gravatar_id":"","url":"https://api.github.com/users/lmangani","html_url":"https://github.com/lmangani","followers_url":"https://api.github.com/users/lmangani/followers","following_url":"https://api.github.com/users/lmangani/following{/other_user}","gists_url":"https://api.github.com/users/lmangani/gists{/gist_id}","starred_url":"https://api.github.com/users/lmangani/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lmangani/subscriptions","organizations_url":"https://api.github.com/users/lmangani/orgs","repos_url":"https://api.github.com/users/lmangani/repos","events_url":"https://api.github.com/users/lmangani/events{/privacy}","received_events_url":"https://api.github.com/users/lmangani/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2020-10-24T13:16:34Z","updated_at":"2020-10-24T14:45:01Z","closed_at":"2020-10-24T14:45:01Z","author_association":"NONE","active_lock_reason":null,"body":"Hello @regel  & All,\r\n\r\nTesting release 1.6.0 after a long time (installed via yum packages, managed through the grafana integration) and I noticed any successful training consistently fails being stored at the process tail with the following error, apparently regardless of the bucket settings/range:\r\n\r\n```\r\n127.0.0.1 - - [2020-10-24 15:11:25] \"GET /models/hepic_hepic_statistics_calls_mean_finished__time_5m HTTP/1.1\" 200 701 0.002114\r\n100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:00<00:00,  6.01s/it, best loss: 18.589042263891084]\r\nERROR:root:('Not JSON Serializable:', b'\\n\\x11SquaredDifference\\x12\\x11SquaredDifference\\x1a\\x17decoder_dense_2/BiasAdd\\x1a\\x07input_1*\\x07\\n\\x01T\\x12\\x020\\x01')\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.6/site-packages/loudml-1.6.0-py3.6.egg/loudml/worker.py\", line 53, in run\r\n    res = getattr(self, func_name)(*args, **kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/loudml-1.6.0-py3.6.egg/loudml/worker.py\", line 101, in train\r\n    **kwargs\r\n  File \"/usr/local/lib/python3.6/site-packages/loudml-1.6.0-py3.6.egg/loudml/donut.py\", line 1101, in train\r\n    model_b64 = _serialize_keras_model(self._keras_model)\r\n  File \"/usr/local/lib/python3.6/site-packages/loudml-1.6.0-py3.6.egg/loudml/donut.py\", line 228, in _serialize_keras_model\r\n    keras_model.save(path)\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py\", line 1211, in save\r\n    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py\", line 113, in save_model\r\n    model, filepath, overwrite, include_optimizer)\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py\", line 101, in save_model_to_hdf5\r\n    default=serialization.get_json_type).encode('utf8')\r\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 238, in dumps\r\n    **kw).encode(obj)\r\n  File \"/usr/lib64/python3.6/json/encoder.py\", line 199, in encode\r\n    chunks = self.iterencode(o, _one_shot=True)\r\n  File \"/usr/lib64/python3.6/json/encoder.py\", line 257, in iterencode\r\n    return _iterencode(o, 0)\r\n  File \"/usr/local/lib/python3.6/site-packages/tensorflow/python/util/serialization.py\", line 69, in get_json_type\r\n    raise TypeError('Not JSON Serializable:', obj)\r\nTypeError: ('Not JSON Serializable:', b'\\n\\x11SquaredDifference\\x12\\x11SquaredDifference\\x1a\\x17decoder_dense_2/BiasAdd\\x1a\\x07input_1*\\x07\\n\\x01T\\x12\\x020\\x01')\r\nERROR:root:job[469672de-928b-4424-b5bc-3935fdd665ad] failed: ('Not JSON Serializable:', b'\\n\\x11SquaredDifference\\x12\\x11SquaredDifference\\x1a\\x17decoder_dense_2/BiasAdd\\x1a\\x07input_1*\\x07\\n\\x01T\\x12\\x020\\x01')\r\n```\r\n\r\nDid anyone else experience the same and/or has a clue as of what might be causing this?\r\n\r\nThanks in advance!","closed_by":{"login":"lmangani","id":1423657,"node_id":"MDQ6VXNlcjE0MjM2NTc=","avatar_url":"https://avatars.githubusercontent.com/u/1423657?v=4","gravatar_id":"","url":"https://api.github.com/users/lmangani","html_url":"https://github.com/lmangani","followers_url":"https://api.github.com/users/lmangani/followers","following_url":"https://api.github.com/users/lmangani/following{/other_user}","gists_url":"https://api.github.com/users/lmangani/gists{/gist_id}","starred_url":"https://api.github.com/users/lmangani/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lmangani/subscriptions","organizations_url":"https://api.github.com/users/lmangani/orgs","repos_url":"https://api.github.com/users/lmangani/repos","events_url":"https://api.github.com/users/lmangani/events{/privacy}","received_events_url":"https://api.github.com/users/lmangani/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/regel/loudml/issues/456/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/regel/loudml/issues/456/timeline","performed_via_github_app":null,"state_reason":"completed"}