{"url":"https://api.github.com/repos/NUAA-AL/ALiPy/issues/3","repository_url":"https://api.github.com/repos/NUAA-AL/ALiPy","labels_url":"https://api.github.com/repos/NUAA-AL/ALiPy/issues/3/labels{/name}","comments_url":"https://api.github.com/repos/NUAA-AL/ALiPy/issues/3/comments","events_url":"https://api.github.com/repos/NUAA-AL/ALiPy/issues/3/events","html_url":"https://github.com/NUAA-AL/ALiPy/issues/3","id":412692492,"node_id":"MDU6SXNzdWU0MTI2OTI0OTI=","number":3,"title":"Possible bug in get_query_strategy inside toolbox.py","user":{"login":"Arshita27","id":39977250,"node_id":"MDQ6VXNlcjM5OTc3MjUw","avatar_url":"https://avatars.githubusercontent.com/u/39977250?v=4","gravatar_id":"","url":"https://api.github.com/users/Arshita27","html_url":"https://github.com/Arshita27","followers_url":"https://api.github.com/users/Arshita27/followers","following_url":"https://api.github.com/users/Arshita27/following{/other_user}","gists_url":"https://api.github.com/users/Arshita27/gists{/gist_id}","starred_url":"https://api.github.com/users/Arshita27/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Arshita27/subscriptions","organizations_url":"https://api.github.com/users/Arshita27/orgs","repos_url":"https://api.github.com/users/Arshita27/repos","events_url":"https://api.github.com/users/Arshita27/events{/privacy}","received_events_url":"https://api.github.com/users/Arshita27/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2019-02-21T00:26:58Z","updated_at":"2019-03-01T09:57:19Z","closed_at":"2019-03-01T09:57:19Z","author_association":"NONE","active_lock_reason":null,"body":"https://github.com/NUAA-AL/ALiPy/blob/71d716d2406c105556596f1e44442160d9a00d27/alipy/toolbox.py#L402-L409\r\n\r\nWhen I tried to run ''QueryInstanceGraphDensity' it gave me an error: \"Missing key 'train_idx' \", even when I was providing this key.\r\n\r\nOne possible bug could be that in line 402, kwargs.pop('train_idx', None) is being called which removes the train_idx key from the dictionary. Thus when it is called again in line 408, it gives an error as the key is no longer present due to the previous 'pop' statement. \r\n\r\nDo let me know if I am missing out anything.\r\n\r\n ","closed_by":{"login":"tangypnuaa","id":40466308,"node_id":"MDQ6VXNlcjQwNDY2MzA4","avatar_url":"https://avatars.githubusercontent.com/u/40466308?v=4","gravatar_id":"","url":"https://api.github.com/users/tangypnuaa","html_url":"https://github.com/tangypnuaa","followers_url":"https://api.github.com/users/tangypnuaa/followers","following_url":"https://api.github.com/users/tangypnuaa/following{/other_user}","gists_url":"https://api.github.com/users/tangypnuaa/gists{/gist_id}","starred_url":"https://api.github.com/users/tangypnuaa/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tangypnuaa/subscriptions","organizations_url":"https://api.github.com/users/tangypnuaa/orgs","repos_url":"https://api.github.com/users/tangypnuaa/repos","events_url":"https://api.github.com/users/tangypnuaa/events{/privacy}","received_events_url":"https://api.github.com/users/tangypnuaa/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/NUAA-AL/ALiPy/issues/3/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/NUAA-AL/ALiPy/issues/3/timeline","performed_via_github_app":null,"state_reason":"completed"}