{"url":"https://api.github.com/repos/jgraving/DeepPoseKit/issues/29","repository_url":"https://api.github.com/repos/jgraving/DeepPoseKit","labels_url":"https://api.github.com/repos/jgraving/DeepPoseKit/issues/29/labels{/name}","comments_url":"https://api.github.com/repos/jgraving/DeepPoseKit/issues/29/comments","events_url":"https://api.github.com/repos/jgraving/DeepPoseKit/issues/29/events","html_url":"https://github.com/jgraving/DeepPoseKit/issues/29","id":523173151,"node_id":"MDU6SXNzdWU1MjMxNzMxNTE=","number":29,"title":"Predict on images that are different size than training data","user":{"login":"PranavMaddula","id":6210333,"node_id":"MDQ6VXNlcjYyMTAzMzM=","avatar_url":"https://avatars.githubusercontent.com/u/6210333?v=4","gravatar_id":"","url":"https://api.github.com/users/PranavMaddula","html_url":"https://github.com/PranavMaddula","followers_url":"https://api.github.com/users/PranavMaddula/followers","following_url":"https://api.github.com/users/PranavMaddula/following{/other_user}","gists_url":"https://api.github.com/users/PranavMaddula/gists{/gist_id}","starred_url":"https://api.github.com/users/PranavMaddula/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/PranavMaddula/subscriptions","organizations_url":"https://api.github.com/users/PranavMaddula/orgs","repos_url":"https://api.github.com/users/PranavMaddula/repos","events_url":"https://api.github.com/users/PranavMaddula/events{/privacy}","received_events_url":"https://api.github.com/users/PranavMaddula/received_events","type":"User","site_admin":false},"labels":[{"id":1348126484,"node_id":"MDU6TGFiZWwxMzQ4MTI2NDg0","url":"https://api.github.com/repos/jgraving/DeepPoseKit/labels/enhancement","name":"enhancement","color":"a2eeef","default":true,"description":"New feature or request"},{"id":1348126491,"node_id":"MDU6TGFiZWwxMzQ4MTI2NDkx","url":"https://api.github.com/repos/jgraving/DeepPoseKit/labels/question","name":"question","color":"d876e3","default":true,"description":"Further information is requested"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2019-11-14T23:57:58Z","updated_at":"2019-11-18T09:58:46Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"From the steps in the 'DeepPoseKit Step 3 - Train a model' I have trained a model for locust pose mapping. However, the data used in the annotation set is 160x160. When following the steps in the 'DeepPoseKit Step 4b - Predict on new data' notebook, I get the following issue:\r\n\r\n`reader = VideoReader(HOME + '/Data/crop.mp4', batch_size=50, gray=True)\r\npredictions = model.predict(reader, verbose=1)\r\nreader.close()`\r\n\r\n`---------------------------------------------------------------------------\r\nValueError                                Traceback (most recent call last)\r\n<ipython-input-11-d79f7abc10a7> in <module>\r\n      1 reader = VideoReader(HOME + '/Data/crop.mp4', batch_size=50, gray=True)\r\n----> 2 predictions = model.predict(reader, verbose=1)\r\n      3 reader.close()\r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)\r\n    907         max_queue_size=max_queue_size,\r\n    908         workers=workers,\r\n--> 909         use_multiprocessing=use_multiprocessing)\r\n    910 \r\n    911   def reset_metrics(self):\r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training_generator.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)\r\n    646         max_queue_size=max_queue_size,\r\n    647         workers=workers,\r\n--> 648         use_multiprocessing=use_multiprocessing)\r\n    649 \r\n    650 \r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)\r\n    263 \r\n    264       is_deferred = not model._is_compiled\r\n--> 265       batch_outs = batch_function(*batch_data)\r\n    266       if not isinstance(batch_outs, list):\r\n    267         batch_outs = [batch_outs]\r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training_generator.py in predict_on_batch(x, y, sample_weights)\r\n    533     # 1, 2, or 3-tuples from generator\r\n    534     def predict_on_batch(x, y=None, sample_weights=None):  # pylint: disable=unused-argument\r\n--> 535       return model.predict_on_batch(x)\r\n    536 \r\n    537     f = predict_on_batch\r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training.py in predict_on_batch(self, x)\r\n   1142     # Validate and standardize user data.\r\n   1143     inputs, _, _ = self._standardize_user_data(\r\n-> 1144         x, extract_tensors_from_dataset=True)\r\n   1145     # If `self._distribution_strategy` is True, then we are in a replica context\r\n   1146     # at this point.\r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)\r\n   2470           feed_input_shapes,\r\n   2471           check_batch_axis=False,  # Don't enforce the batch size.\r\n-> 2472           exception_prefix='input')\r\n   2473 \r\n   2474     # Get typespecs for the input data and sanitize it if necessary.\r\n\r\n~\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)\r\n    572                              ': expected ' + names[i] + ' to have shape ' +\r\n    573                              str(shape) + ' but got array with shape ' +\r\n--> 574                              str(data_shape))\r\n    575   return data\r\n    576 \r\n\r\n**ValueError: Error when checking input: expected input_1 to have shape (160, 160, 1) but got array with shape (512, 512, 1)`**\r\n\r\n\r\n\r\nI assume that this is because the model was trained on 160x160 pixel images, while I would like to predict on 512x512 images. I have tried to resize the densenet model with Keras using the following methods:\r\n\r\n`from kerassurgeon.operations import delete_layer, insert_layer\r\nmy_input_tensor = Input(input_shape=(512, 512, 1))\r\nfrom tfkerassurgeon import delete_layer, insert_layer\r\nmodel = delete_layer(model.layers[0])\r\nmodel = insert_layer(model.layers[0], my_input_tensor)\r\n`\r\nalong with `keras.add`, `model.layers`, and `model.inputs` to no avail.\r\n\r\nIs there an easy way to resize the model for inference/prediction? Or will I have to re-train the model on 512x512 images?\r\n\r\nThanks!","closed_by":{"login":"jgraving","id":5445636,"node_id":"MDQ6VXNlcjU0NDU2MzY=","avatar_url":"https://avatars.githubusercontent.com/u/5445636?v=4","gravatar_id":"","url":"https://api.github.com/users/jgraving","html_url":"https://github.com/jgraving","followers_url":"https://api.github.com/users/jgraving/followers","following_url":"https://api.github.com/users/jgraving/following{/other_user}","gists_url":"https://api.github.com/users/jgraving/gists{/gist_id}","starred_url":"https://api.github.com/users/jgraving/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jgraving/subscriptions","organizations_url":"https://api.github.com/users/jgraving/orgs","repos_url":"https://api.github.com/users/jgraving/repos","events_url":"https://api.github.com/users/jgraving/events{/privacy}","received_events_url":"https://api.github.com/users/jgraving/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/jgraving/DeepPoseKit/issues/29/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/jgraving/DeepPoseKit/issues/29/timeline","performed_via_github_app":null,"state_reason":null}