{"url":"https://api.github.com/repos/xavierpuigf/virtualhome/issues/2","repository_url":"https://api.github.com/repos/xavierpuigf/virtualhome","labels_url":"https://api.github.com/repos/xavierpuigf/virtualhome/issues/2/labels{/name}","comments_url":"https://api.github.com/repos/xavierpuigf/virtualhome/issues/2/comments","events_url":"https://api.github.com/repos/xavierpuigf/virtualhome/issues/2/events","html_url":"https://github.com/xavierpuigf/virtualhome/issues/2","id":461884431,"node_id":"MDU6SXNzdWU0NjE4ODQ0MzE=","number":2,"title":"cannot render_script","user":{"login":"jolinxql","id":5552657,"node_id":"MDQ6VXNlcjU1NTI2NTc=","avatar_url":"https://avatars.githubusercontent.com/u/5552657?v=4","gravatar_id":"","url":"https://api.github.com/users/jolinxql","html_url":"https://github.com/jolinxql","followers_url":"https://api.github.com/users/jolinxql/followers","following_url":"https://api.github.com/users/jolinxql/following{/other_user}","gists_url":"https://api.github.com/users/jolinxql/gists{/gist_id}","starred_url":"https://api.github.com/users/jolinxql/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jolinxql/subscriptions","organizations_url":"https://api.github.com/users/jolinxql/orgs","repos_url":"https://api.github.com/users/jolinxql/repos","events_url":"https://api.github.com/users/jolinxql/events{/privacy}","received_events_url":"https://api.github.com/users/jolinxql/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2019-06-28T06:47:11Z","updated_at":"2019-07-02T19:25:12Z","closed_at":"2019-07-02T19:25:12Z","author_association":"NONE","active_lock_reason":null,"body":"Hi, \r\nI can successfully run all scripts in [unity_demo.ipynb](https://github.com/xavierpuigf/virtualhome/blob/master/demo/unity_demo.ipynb) **except lines containing `render_script`.**\r\nI always get the following error when I try to `render_script`:\r\n```\r\n------------------------------------------------------------\r\nUnityEngineException       Traceback (most recent call last)\r\n<ipython-input-33-b0a2016e0ac0> in <module>()\r\n     13                                       image_width=512, image_height=320,\r\n     14                                       file_name_prefix='milk',\r\n---> 15                                       camera_mode='FIRST_PERSON')\r\n\r\n~/Source/virtualhome/simulation/unity_simulator/comm_unity.py in render_script(self, script, randomize_execution, random_seed, processing_time_limit, skip_execution, find_solution, output_folder, file_name_prefix, frame_rate, image_synthesis, capture_screenshot, save_pose_data, image_width, image_height, gen_vid, save_scene_states, character_resource, camera_mode)\r\n    141                   'image_width': image_width, 'image_height': image_height}\r\n    142         response = self.post_command({'id': str(time.time()), 'action': 'render_script',\r\n--> 143                                       'stringParams': [json.dumps(params)] + script})\r\n    144         if response['success']:\r\n    145             if gen_vid and len(image_synthesis) > 0:\r\n\r\n~/Source/virtualhome/simulation/unity_simulator/comm_unity.py in post_command(self, request_dict)\r\n     19             resp = requests.post(self._address, json=request_dict)\r\n     20             if resp.status_code != requests.codes.ok:\r\n---> 21                 raise UnityEngineException(resp.status_code, resp.json())\r\n     22             return resp.json()\r\n     23         except requests.exceptions.RequestException as e:\r\n\r\nUnityEngineException: (408, {'id': '1561703596.590129', 'success': False, 'message': 'Timeout', 'value': 0, 'message_list': None})\r\n```\r\nI'm using Ubuntu 18.04 remotely.\r\nI have also tried docker. I can run [generate_snapshot.py](https://github.com/xavierpuigf/virtualhome/blob/master/demo/generate_snapshot.py) inside or outside the docker and successfully get all the snapshots.\r\nBut I always get the same error when running [generate_video.py](https://github.com/xavierpuigf/virtualhome/blob/master/demo/generate_video.py), always stuck at `render_script` function.\r\nCould you please help me?","closed_by":{"login":"xavierpuigf","id":4203263,"node_id":"MDQ6VXNlcjQyMDMyNjM=","avatar_url":"https://avatars.githubusercontent.com/u/4203263?v=4","gravatar_id":"","url":"https://api.github.com/users/xavierpuigf","html_url":"https://github.com/xavierpuigf","followers_url":"https://api.github.com/users/xavierpuigf/followers","following_url":"https://api.github.com/users/xavierpuigf/following{/other_user}","gists_url":"https://api.github.com/users/xavierpuigf/gists{/gist_id}","starred_url":"https://api.github.com/users/xavierpuigf/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/xavierpuigf/subscriptions","organizations_url":"https://api.github.com/users/xavierpuigf/orgs","repos_url":"https://api.github.com/users/xavierpuigf/repos","events_url":"https://api.github.com/users/xavierpuigf/events{/privacy}","received_events_url":"https://api.github.com/users/xavierpuigf/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/xavierpuigf/virtualhome/issues/2/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/xavierpuigf/virtualhome/issues/2/timeline","performed_via_github_app":null,"state_reason":"completed"}