{"url":"https://api.github.com/repos/ultralytics/yolov3/issues/454","repository_url":"https://api.github.com/repos/ultralytics/yolov3","labels_url":"https://api.github.com/repos/ultralytics/yolov3/issues/454/labels{/name}","comments_url":"https://api.github.com/repos/ultralytics/yolov3/issues/454/comments","events_url":"https://api.github.com/repos/ultralytics/yolov3/issues/454/events","html_url":"https://github.com/ultralytics/yolov3/issues/454","id":480973034,"node_id":"MDU6SXNzdWU0ODA5NzMwMzQ=","number":454,"title":"RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.","user":{"login":"XiaoJiNu","id":30587645,"node_id":"MDQ6VXNlcjMwNTg3NjQ1","avatar_url":"https://avatars.githubusercontent.com/u/30587645?v=4","gravatar_id":"","url":"https://api.github.com/users/XiaoJiNu","html_url":"https://github.com/XiaoJiNu","followers_url":"https://api.github.com/users/XiaoJiNu/followers","following_url":"https://api.github.com/users/XiaoJiNu/following{/other_user}","gists_url":"https://api.github.com/users/XiaoJiNu/gists{/gist_id}","starred_url":"https://api.github.com/users/XiaoJiNu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/XiaoJiNu/subscriptions","organizations_url":"https://api.github.com/users/XiaoJiNu/orgs","repos_url":"https://api.github.com/users/XiaoJiNu/repos","events_url":"https://api.github.com/users/XiaoJiNu/events{/privacy}","received_events_url":"https://api.github.com/users/XiaoJiNu/received_events","type":"User","site_admin":false},"labels":[{"id":1035696370,"node_id":"MDU6TGFiZWwxMDM1Njk2Mzcw","url":"https://api.github.com/repos/ultralytics/yolov3/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2019-08-15T03:01:02Z","updated_at":"2019-08-15T09:21:55Z","closed_at":"2019-08-15T09:21:55Z","author_association":"NONE","active_lock_reason":null,"body":"Hi, when I used pytorch1.2  it outputed bug as follows:\r\nRuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.\r\nBut when I used pytorch1.0 it was ok. What's the problem?\r\n","closed_by":{"login":"glenn-jocher","id":26833433,"node_id":"MDQ6VXNlcjI2ODMzNDMz","avatar_url":"https://avatars.githubusercontent.com/u/26833433?v=4","gravatar_id":"","url":"https://api.github.com/users/glenn-jocher","html_url":"https://github.com/glenn-jocher","followers_url":"https://api.github.com/users/glenn-jocher/followers","following_url":"https://api.github.com/users/glenn-jocher/following{/other_user}","gists_url":"https://api.github.com/users/glenn-jocher/gists{/gist_id}","starred_url":"https://api.github.com/users/glenn-jocher/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/glenn-jocher/subscriptions","organizations_url":"https://api.github.com/users/glenn-jocher/orgs","repos_url":"https://api.github.com/users/glenn-jocher/repos","events_url":"https://api.github.com/users/glenn-jocher/events{/privacy}","received_events_url":"https://api.github.com/users/glenn-jocher/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/ultralytics/yolov3/issues/454/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/ultralytics/yolov3/issues/454/timeline","performed_via_github_app":null,"state_reason":"completed"}