{"url":"https://api.github.com/repos/mlflow/mlflow/issues/3203","repository_url":"https://api.github.com/repos/mlflow/mlflow","labels_url":"https://api.github.com/repos/mlflow/mlflow/issues/3203/labels{/name}","comments_url":"https://api.github.com/repos/mlflow/mlflow/issues/3203/comments","events_url":"https://api.github.com/repos/mlflow/mlflow/issues/3203/events","html_url":"https://github.com/mlflow/mlflow/issues/3203","id":669311147,"node_id":"MDU6SXNzdWU2NjkzMTExNDc=","number":3203,"title":"[BUG] Too many connections while using AWS RDS as backend","user":{"login":"murphycj","id":3837196,"node_id":"MDQ6VXNlcjM4MzcxOTY=","avatar_url":"https://avatars.githubusercontent.com/u/3837196?v=4","gravatar_id":"","url":"https://api.github.com/users/murphycj","html_url":"https://github.com/murphycj","followers_url":"https://api.github.com/users/murphycj/followers","following_url":"https://api.github.com/users/murphycj/following{/other_user}","gists_url":"https://api.github.com/users/murphycj/gists{/gist_id}","starred_url":"https://api.github.com/users/murphycj/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/murphycj/subscriptions","organizations_url":"https://api.github.com/users/murphycj/orgs","repos_url":"https://api.github.com/users/murphycj/repos","events_url":"https://api.github.com/users/murphycj/events{/privacy}","received_events_url":"https://api.github.com/users/murphycj/received_events","type":"User","site_admin":false},"labels":[{"id":955449428,"node_id":"MDU6TGFiZWw5NTU0NDk0Mjg=","url":"https://api.github.com/repos/mlflow/mlflow/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"},{"id":2022849295,"node_id":"MDU6TGFiZWwyMDIyODQ5Mjk1","url":"https://api.github.com/repos/mlflow/mlflow/labels/area/tracking","name":"area/tracking","color":"48eabc","default":false,"description":"Tracking service, tracking client APIs, autologging"},{"id":2022852620,"node_id":"MDU6TGFiZWwyMDIyODUyNjIw","url":"https://api.github.com/repos/mlflow/mlflow/labels/area/sqlalchemy","name":"area/sqlalchemy","color":"ede978","default":false,"description":"Use of SQL alchemy in tracking service or model registry"}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2020-07-31T00:58:17Z","updated_at":"2021-09-15T20:21:17Z","closed_at":"2021-09-15T20:21:16Z","author_association":"NONE","active_lock_reason":null,"body":"### Willingness to contribute\r\n- [ ] Yes. I can contribute a fix for this bug independently.\r\n- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.\r\n- [ ] No. I cannot contribute a bug fix at this time.\r\n\r\n### System information\r\n- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: \r\nNo\r\n- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:\r\nLinux 4.14.181-142.260.amzn2.x86_64\r\n- **MLflow installed from (source or binary)**:\r\npip install mlflow\r\n- **MLflow version (run ``mlflow --version``)**:\r\n1.10.0\r\n- **Python version**:\r\n3.7.7\r\n- **npm version, if running the dev UI**:\r\nNA\r\n- **Exact command to reproduce**:\r\n\r\n### Describe the problem\r\nApologies if this is a duplicate. I did see a similar issue (#1565), but the solution is unclear. I also see this issue #2650 but I am not sure if it is the same as mine. So I though I'd post my issue.\r\n\r\nI am using AWS-RDS (postgresql) as a backend for mlflow while training with tensorflow/keras on EC2 instances. Also note that I am using talos ([github](https://github.com/autonomio/talos)) for parameter optimization. Everything runs fine with just one worker running, but if I have 2+ workers running on separate EC2 instances then I get this error indicating the RDS database has too many connections. See the error message produce by mlflow below.\r\n\r\n<details><summary>Click for error message</summary>\r\n<p>\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 2280, in _wrap_pool_connect\r\n    e, dialect, self\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 1547, in _handle_dbapi_exception_noconnection\r\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/util/compat.py\", line 398, in raise_from_cause\r\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/util/compat.py\", line 152, in reraise\r\n    raise value.with_traceback(tb)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 2276, in _wrap_pool_connect\r\n    return fn()\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 303, in unique_connection\r\n    return _ConnectionFairy._checkout(self)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 773, in _checkout\r\n    fairy = _ConnectionRecord.checkout(pool)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 492, in checkout\r\n    rec = pool._do_get()\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/impl.py\", line 139, in _do_get\r\n    self._dec_overflow()\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py\", line 68, in __exit__\r\n    compat.reraise(exc_type, exc_value, exc_tb)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/util/compat.py\", line 153, in reraise\r\n    raise value\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/impl.py\", line 136, in _do_get\r\n    return self._create_connection()\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 308, in _create_connection\r\n    return _ConnectionRecord(self)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 437, in __init__\r\n    self.__connect(first_connect_check=True)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 652, in __connect\r\n    connection = pool._invoke_creator(self)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py\", line 114, in connect\r\n    return dialect.connect(*cargs, **cparams)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sqlalchemy/engine/default.py\", line 489, in connect\r\n    return self.dbapi.connect(*cargs, **cparams)\r\n  File \"/home/ec2-user/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/psycopg2/__init__.py\", line 130, in connect\r\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\r\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections\r\n```\r\n\r\n</p>\r\n</details>\r\n\r\nI also attached a screenshot from AWS RDS dashboard showing the number of connections overtime (note the screenshot was when I had only one mlflow worker running). I would expect there to just be two connections: one from EC2 worker and one from mlflow UI server, but I instead see 50+.\r\n<img width=\"961\" alt=\"Screen Shot 2020-07-30 at 8 35 00 PM\" src=\"https://user-images.githubusercontent.com/3837196/88987580-6b023e00-d2a4-11ea-850d-6bdc03426148.png\">\r\n\r\n### Code to reproduce issue\r\nHere is a distilled down version of the code I am running to give you an idea of how I am doing this:\r\n\r\n```python\r\nimport json\r\n\r\nfrom sklearn.model_selection import train_test_split\r\nimport tensorflow as tf\r\nimport mlflow\r\nfrom mlflow import tensorflow as mlt\r\nimport talos\r\n\r\ntf.config.threading.set_intra_op_parallelism_threads(8)\r\ntf.config.threading.set_inter_op_parallelism_threads(8)\r\nAUTOTUNE = tf.data.experimental.AUTOTUNE\r\n\r\nconfig = json.load(open('config.json'))\r\n\r\nmlflow.set_tracking_uri(\r\n    'postgresql://{}:{}@{}:{}/mlflow'.format(\r\n        config['db']['USER'],\r\n        config['db']['PASSWORD'],\r\n        config['db']['HOST'],\r\n        config['db']['PORT']\r\n    ))\r\nmlt.autolog(1)\r\n\r\ndef model_scan(x_train, y_train, x_val, y_val, params):\r\n\r\n    with mlflow.start_run(experiment_id='9'):\r\n\r\n        for name, val in params.items():\r\n            mlflow.log_param(name, val)\r\n\r\n        dataset = load_data(x_train, y_train, params)\r\n        dataset_test = load_data(x_val, y_val, params)\r\n\r\n        dataset = dataset.prefetch(buffer_size=AUTOTUNE)\r\n        dataset_test = dataset_test.prefetch(buffer_size=AUTOTUNE)\r\n\r\n        model = model1(params)\r\n        model_history = model.fit(\r\n            dataset.repeat().batch(params['batch_size']),\r\n            epochs=params['epochs'],\r\n            steps_per_epoch=params['steps_per_epoch'],\r\n            validation_data=dataset_val.batch(params['batch_size']),\r\n            validation_freq=params['validation_freq'],\r\n            callbacks=[\r\n                MetricCallback(),\r\n                talos.utils.early_stopper(params['epochs'])\r\n                ])\r\n\r\n    return model_history, model\r\n\r\nx_train, x_val, y_train, y_val = train_test_split(X, y, test_size=0.1)\r\n\r\nscan_object = talos.Scan(\r\n    x=x_train,\r\n    y=y_train,\r\n    model=model_scan,\r\n    params=params,\r\n    fraction_limit=0.1,\r\n    x_val=x_val,\r\n    y_val=y_val,\r\n    experiment_name='',\r\n    random_method='quantum')\r\n```\r\n\r\n### What component(s), interfaces, languages, and integrations does this bug affect?\r\nComponents \r\n- [ ] `area/artifacts`: Artifact stores and artifact logging\r\n- [ ] `area/build`: Build and test infrastructure for MLflow\r\n- [ ] `area/docs`: MLflow documentation pages\r\n- [ ] `area/examples`: Example code\r\n- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry\r\n- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors\r\n- [ ] `area/projects`: MLproject format, project running backends\r\n- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs\r\n- [ ] `area/server-infra`: MLflow server, JavaScript dev server\r\n- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging\r\n\r\nInterface \r\n- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting\r\n- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models\r\n- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry\r\n- [ ] `area/windows`: Windows support","closed_by":{"login":"dbczumar","id":39497902,"node_id":"MDQ6VXNlcjM5NDk3OTAy","avatar_url":"https://avatars.githubusercontent.com/u/39497902?v=4","gravatar_id":"","url":"https://api.github.com/users/dbczumar","html_url":"https://github.com/dbczumar","followers_url":"https://api.github.com/users/dbczumar/followers","following_url":"https://api.github.com/users/dbczumar/following{/other_user}","gists_url":"https://api.github.com/users/dbczumar/gists{/gist_id}","starred_url":"https://api.github.com/users/dbczumar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dbczumar/subscriptions","organizations_url":"https://api.github.com/users/dbczumar/orgs","repos_url":"https://api.github.com/users/dbczumar/repos","events_url":"https://api.github.com/users/dbczumar/events{/privacy}","received_events_url":"https://api.github.com/users/dbczumar/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/mlflow/mlflow/issues/3203/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/mlflow/mlflow/issues/3203/timeline","performed_via_github_app":null,"state_reason":"completed"}